name: mazzraati_vendor_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animated_floating_buttons: ^0.0.2
  autocomplete_textfield: ^2.0.1
  barcode_widget: ^2.0.4
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  connectivity_plus: ^6.1.3
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  dotted_border: ^2.1.0
  esc_pos_utils: ^1.1.0
  file_picker: ^8.1.2
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_downloader: 1.11.7
  flutter_html: ^3.0.0-alpha.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_pos_printer_platform_image_3_sdt: ^1.1.3
  flutter_slidable: ^3.0.1
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.0.0
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get: ^4.6.6
  get_it: ^7.6.4
  google_maps_flutter: ^2.9.0
  http: ^1.1.2
  http_parser: ^4.0.2
  image_picker: ^1.0.5
  intl: ^0.19.0
  logger: ^2.4.0
  open_file: ^3.5.10
  open_file_manager: ^1.0.2
  path: ^1.8.2
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  permission_handler: ^11.1.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.1
  readmore: ^2.2.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  syncfusion_flutter_datepicker: ^24.1.44
  textfield_tags: 2.0.2
  typed_data: ^1.3.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: null

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
# icons_launcher:
#   image_path: "assets/image/ic_launcher.png"
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true
#     macos:
#       enable: true
flutter_icons:
  ios: true
  android: true
  image_path: "assets/image/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/ubuntu/Ubuntu-Bold.ttf
          weight: 600

    - family: AminFamily
      fonts:
        - asset: assets/font/Amin Family/Amin Font Bold.otf
          weight: 700
        - asset: assets/font/Amin Family/Amin Font Medium_0.otf
          weight: 500
        - asset: assets/font/Amin Family/Amin Font Regular_1.otf
          weight: 400

    - family: DINNextLTArabic
      fonts:
        - asset: assets/font/Din Next Lt Arabic Family/Din Next Lt Arabic Light.otf
          weight: 300
        - asset: assets/font/Din Next Lt Arabic Family/DINNextLTArabic-Black.ttf
          weight: 900
        - asset: assets/font/Din Next Lt Arabic Family/DINNextLTArabic-Bold.ttf
          weight: 700
        - asset: assets/font/Din Next Lt Arabic Family/DINNextLTArabic-Heavy.ttf
          weight: 800
        - asset: assets/font/Din Next Lt Arabic Family/DINNextLTArabic-Medium.ttf
          weight: 500
        - asset: assets/font/Din Next Lt Arabic Family/DINNextLTArabic-Regular.ttf
          weight: 400
        - asset: assets/font/Din Next Lt Arabic Family/DINNextLTArabic-UltraLight.ttf
          weight: 200
