// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD57bzQp-wwWq2tZDtc82x7sNAsHTBw1Ho',
    appId: '1:271380736469:android:ea6df8062ca0d6d9a3755c',
    messagingSenderId: '271380736469',
    projectId: 'beytiarabia',
    databaseURL: 'https://beytiarabia-default-rtdb.firebaseio.com',
    storageBucket: 'beytiarabia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD85M3foh7pZqcVbO8hVL15gNTYW13M0a0',
    appId: '1:271380736469:ios:c6ee920fc3196745a3755c',
    messagingSenderId: '271380736469',
    projectId: 'beytiarabia',
    databaseURL: 'https://beytiarabia-default-rtdb.firebaseio.com',
    storageBucket: 'beytiarabia.appspot.com',
    androidClientId: '271380736469-8jk7gk9r46l6rd0qdb3k8pp8l57m0led.apps.googleusercontent.com',
    iosBundleId: 'com.mazzraati.vendor',
  );

}